### ISSUE TITLE
Xforms very slow

### ISSUE THREAD

**Issue by jaredalexander** [nyaruka/rapidsms-xforms#8]
I have RapidSMS running on a server, with XForms installed (both latest
 versions).  I have ingested 4438 messages into the system.  When I log in
 and click the XForms tab, then click "Submissions", I have to wait over 5
 minutes to view the results.  In addition, it takes even more time when
 using XForms to export to CSV.  ~4K records doesn't seem that big to me.
  The server has 2 GB memory, single core 2.5 ghz cpu.  When I copy the
 sqlite file locally and open with a sqlite reader, I can do a select \* query
 on it in less than a second.   When I open the sqlite db on the server using
 shell sqlite commands, I can do a select \* in a few seconds (no joins).  I
 am sure that XForms uses joins to display the messages appropriately on the
 website.

My form fields are:

month (int)
day(int)
year(int)
hour(int)
minute(int)
id(int)
disease (text)
count (int)

I do not have any constraints.  You may wonder why I have the time fields.  It is because we were doing some simulations, so we needed to store a time different than the timestamp auto generated by rapidsms/xforms.

 Any ideas on why it is so slow to access via XForms in the browser?

 Thanks!
 Jared

**Comment by nicpottier** [comment]
This is fixed in 0.3.5 (about to be released)
